/*
 * This file was generated by the Gradle 'init' task.
 */

//https://plugins.gradle.org/
plugins {
    java
    `maven-publish`
    application
    id("org.openjfx.javafxplugin") version "0.0.10"
}

repositories {
    maven {
        url = uri("https://mavensync.zkoss.org/maven2")
    }

    maven {
        url = uri("https://mavensync.zkoss.org/eval")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

javafx {
    version = "16"
    modules = listOf("javafx.fxml","javafx.web")
}

application {
    mainClass.set("org.zkoss.MyWebView")
}

dependencies {
    implementation("org.zkoss.zk:zkmax:9.6.1-Eval")
    implementation("org.zkoss.zkspringboot:zkspringboot-autoconfig:2.5.12")
    implementation("org.springframework.boot:spring-boot-starter-web:2.5.12")
}

group = "org.zkoss"
version = "1.0-SNAPSHOT"
description = "The zkdesktopapp Project"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

